#!/bin/bash

#############################################################################
#                                                                            #
#  Script para cambiar de directorio de juego                                #
#                                                                            #
#  Creado ReaDeveloper                                                       #
#                                                                            #
##############################################################################

if [ $1 = "minecraft" ];then
	if [ $2 ];then 
		result=$(python3 /usr/mincrft/funciones.py directorio $2)
		
		if [ $result = "Error" ];then
			echo "Directorio no existe"
		else 
			cd $result
		fi
	else 
		python3 /usr/mincrft/funciones.py todosDirectorio
	fi
		
fi