#!/bin/bash

#############################################################################
#                                                                            #
#  Script para cambiar de directorio de juego                                #
#                                                                            #
#  Creado ReaDeveloper                                                       #
#                                                                            #
##############################################################################

if [ $1 = "minecraft" ];then
	case $2 in
		([0-9][0-9] | [0-9] | "e"*)
			if [ -d "$directorioPrincipal$2" ];then
				cd "$directorioPrincipal$2"> /dev/null 2>&1
			else
				echo
				echo "No existe el directorio."
				echo
			fi
		;;
		([0-9]"_"[0-9] | [0-9][0-9]"_"[0-9])
			echo
			echo "Recuerde que los directorios de subversion no existen sino los de version."
			echo "Ejemplo de version: 15."
			echo "Ejemplo de subversion: 15_1."
			echo "Introduzca un numero de version."
			echo
	    ;;
	    ("minecraft")
	    	if [ -d "$directorioPrincipal" ];then
	    			cd "$directorioPrincipal"> /dev/null 2>&1
			else
				echo
				echo "No existe el directorio."
				echo
			fi
	    ;; 
		(*)
			echo
			echo "No ha introducido un numero de version, introduzca un numero de version."
			echo
		;;
	esac
fi