#!/bin/bash

#############################################################################
#                                                                            #
#  Script para cambiar de directorio de juego                                #
#                                                                            #
#  Creado ReaDeveloper                                                       #
#                                                                            #
##############################################################################

if [ $1 = "minecraft" ];then
	if [ $2 ];then 
		result=$(python3 /usr/mincrft/funciones.py directorio $2)
		
		if [ $result = "Error" ];then
			echo "Juego no existe"
		else 
			if [ $result != "" ];then 
				cd $result
			else 
				echo "Se ha producido un error"
			fi
		fi
	else 
		python3 /usr/mincrft/funciones.py todosDirectorio
	fi
		
fi