#!/bin/bash

#############################################################################
#                                                                            #
#  Script para ver log del juego                                             #
#                                                                            #
#  Creado ReaDeveloper                                                       #
#                                                                            #
##############################################################################

if [ $1 = "minecraft" ];then
	if [ $2 ];then 
		result=$(python3 /usr/mincrft/funciones.py log $2)
		
		if [ $result = "Error" ];then
			echo "Juego no existe"
		else 
			if [ $result != "" ];then 
				cat $result
			else 
				echo "Se ha producido un error"
			fi
		fi
	else 
		echo "Falta saber cual juego quiere ver el log. Introduzca el juego"
	fi
fi